application: hack-pea
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /add_note
  script: main.application
- url: /get_score
  script: main.application
- url: /create_score_team
  script: main.application
- url: /list_score_teams
  script: main.application
- url: /register
  script: main.application
- url: /register_mentor
  script: main.application
- url: /interested
  script: main.application
- url: /list
  script: main.application
  login: admin
- url: /delete
  script: main.application
  login: admin
- url: /list.html
  static_files: static/list.html
  upload: static/list.html
  login: admin
- url: /bower_components
  static_dir: static/bower_components
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)
- url: /
  static_files: static/index.html
  upload: static/index.html
